### ISSUE TITLE
You can get stuck in the letter "B" in the giant SUBSCRIBE.

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#10]
Here is a screenshot.

![image](https://user-images.githubusercontent.com/68207888/115167981-6f1af980-a087-11eb-9754-bbdc985abbd1.png)

**Comment by definitely-nobody-is-here** [comment]
That update hasn't been released yet.
You were playing a beta test

**Comment by maitian352** [comment]
Also, you can glitch through walls.

**Comment by definitely-nobody-is-here** [comment]
oof you cant get stuck in the words now but you can still fall through the ground
