### ISSUE TITLE
SUGGESTION - Remove spam detection

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#105]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when [...] i get kicked for typing in the chat

**Describe the solution you'd like**

Remove spam detection

**Describe alternatives you've considered**

Remove chat

**Additional context**

PLEASE FIX

**Comment by definitely-nobody-is-here** [comment]
You were advertising and spamming. You filled the chat with ads.

**Comment by maitian352** [comment]
NO
