### ISSUE TITLE
BUG - Achievements don't save

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [definitely-nobody-is-here/BattleBoxes_Multiplayer#106]
**Describe the bug**
Acheivements no longer save

**To Reproduce**
1. get achievement
2. restart server
3. get achievemetns again

**Expected behavior**

**Screenshots**

**Environment**
 - Browser [e.g. Chrome 90, Safari, Edge]
 - Version [e.g. v0.4.3]

**Additional context**

**Comment by maitian352** [comment]
dfbhghgfdsadfgfhkljhgdsfgh,jhgfdsfghj

**Comment by definitely-nobody-is-here** [comment]
actually, they do save.
