### ISSUE TITLE
You can float on the SUBSCRIBE button

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#11]
![image](https://user-images.githubusercontent.com/68207888/115168804-2284ed80-a08a-11eb-945e-5b5df51a055f.png)

**Comment by definitely-nobody-is-here** [comment]
you are playing a beta test
plus I don't care its a feature

**Comment by maitian352** [comment]
its not a feature its a bug
