### ISSUE TITLE
BUG - scoreboard doesnt reset betwee nrounds

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#120]
this is how this happens
![image](https://user-images.githubusercontent.com/68207888/121810922-94178d00-cc30-11eb-96c9-20048ce53f0c.png)

i win then i press ready then i win again

PLEASE DONT FIX

**Comment by definitely-nobody-is-here** [comment]
you did something wrong. I tested it, won, and started another game. It was fine.

**Comment by maitian352** [comment]
what do you mean? it is a bug
