### ISSUE TITLE
BUG -ACHEVEMENT LINKED BROKEN

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#122]
![image](https://user-images.githubusercontent.com/68207888/121810982-d214b100-cc30-11eb-90be-a0feb6b6c47d.png)
\
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by definitely-nobody-is-here** [comment]
THEY NOT LOINKED

**Comment by definitely-nobody-is-here** [comment]
THAT IS LEFT OVER FROM WHEN THEY WERE LINKED
