### ISSUE TITLE
BUG - win screen gets sent to players not in the game

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#124]
i have three tabs open

they all go in a game and win

then two of them exit and rejoin

then another one wins

bam
the first tab borken

win screen plays twice because the first game and the second

**Comment by maitian352** [comment]
caught a screenshot
![image](https://user-images.githubusercontent.com/68207888/121811485-8c58e800-cc32-11eb-927a-3b0cbb348f4e.png)

**Comment by definitely-nobody-is-here** [comment]
ok
