### ISSUE TITLE
Suggestion: Add a layer for player spawns and a layer for lootboxes

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#133]
it makes making maps easier as you dont have to go ingame to get coordinates.

**Comment by definitely-nobody-is-here** [comment]
who cares I dont need another layer, I can just go look at the tilemap

**Comment by maitian352** [comment]
falsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalsefalse
