### ISSUE TITLE
BUG - two buffs dont stack

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#135]
![image](https://user-images.githubusercontent.com/68207888/122624757-b285ea00-d06f-11eb-9643-e1c0721395ba.png)
my bullets deal 2 damage, not 4

**Comment by definitely-nobody-is-here** [comment]
they cant stack

**Comment by definitely-nobody-is-here** [comment]
thinking about it, they shouldn't stack, and should just refresh the timer
