### ISSUE TITLE
BUG - arena map doesnt load

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#136]
![image](https://user-images.githubusercontent.com/68207888/122624861-27592400-d070-11eb-971d-a4924af0e1e1.png)

i won a game and joined again. aaaaaaaaaaaaa

**Comment by definitely-nobody-is-here** [comment]
fill out template please

**Comment by definitely-nobody-is-here** [comment]
there is no arena map as well
