### ISSUE TITLE
I AM 1% CLOSER TO THE NEXT MAJOR UPDATE

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#139]
hahahahah
![image](https://user-images.githubusercontent.com/68207888/122847073-27a62900-d2d5-11eb-8cf8-ca1af182cd1f.png)
![image](https://user-images.githubusercontent.com/68207888/122847075-283ebf80-d2d5-11eb-8c66-99983da7e788.png)
![image](https://user-images.githubusercontent.com/68207888/122847077-283ebf80-d2d5-11eb-9e7e-6705bdb7e1ca.png)
![image](https://user-images.githubusercontent.com/68207888/122847078-283ebf80-d2d5-11eb-81f9-a7d196b3d22e.png)
![image](https://user-images.githubusercontent.com/68207888/122847079-283ebf80-d2d5-11eb-9297-e265e2dac25d.png)
![image](https://user-images.githubusercontent.com/68207888/122847080-283ebf80-d2d5-11eb-9565-00ff297d3d46.png)
![image](https://user-images.githubusercontent.com/68207888/122847081-283ebf80-d2d5-11eb-8d0d-7e1ae2a21c16.png)
![image](https://user-images.githubusercontent.com/68207888/122847082-283ebf80-d2d5-11eb-9c2b-d030b64e1f07.png)
![image](https://user-images.githubusercontent.com/68207888/122847083-283ebf80-d2d5-11eb-9d84-85b39b3037a3.png)
![image](https://user-images.githubusercontent.com/68207888/122847084-283ebf80-d2d5-11eb-8301-da6dee826f2b.png)
![image](https://user-images.githubusercontent.com/68207888/122847086-283ebf80-d2d5-11eb-88da-9cb31269ac7c.png)
![image](https://user-images.githubusercontent.com/68207888/122847087-283ebf80-d2d5-11eb-9096-fa4c4ffd06ff.png)
![image](https://user-images.githubusercontent.com/68207888/122847088-283ebf80-d2d5-11eb-9acb-ec175d639a5f.png)
![image](https://user-images.githubusercontent.com/68207888/122847090-283ebf80-d2d5-11eb-884d-141d0ff24c41.png)
![image](https://user-images.githubusercontent.com/68207888/122847089-283ebf80-d2d5-11eb-974c-661101024ca4.png)

**Comment by maitian352** [comment]
94% vs 93%
![advancedrubysword](https://user-images.githubusercontent.com/68207888/122847118-35f44500-d2d5-11eb-9bf5-7d23ee13713b.png)
![advancedsteelbow](https://user-images.githubusercontent.com/68207888/122847120-368cdb80-d2d5-11eb-9571-9dad2f7f9834.png)
![advancedsteelstaff](https://user-images.githubusercontent.com/68207888/122847121-368cdb80-d2d5-11eb-9af6-a8c565eec23d.png)
![advancedsteelsword](https://user-images.githubusercontent.com/68207888/122847123-368cdb80-d2d5-11eb-9e36-f36ce4f73306.png)
![advancedwoodenbow](https://user-images.githubusercontent.com/68207888/122847124-368cdb80-d2d5-11eb-87d2-6876554d8839.png)
![advancedwoodenstaff](https://user-images.githubusercontent.com/68207888/122847125-37257200-d2d5-11eb-946f-d7f15076972c.png)
![advancedwoodensword](https://user-images.githubusercontent.com/68207888/122847126-37257200-d2d5-11eb-8ad2-17ad1c0fc797.png)
![ball](https://user-images.githubusercontent.com/68207888/122847127-37257200-d2d5-11eb-8884-b36299464181.png)
![ballBullet](https://user-images.githubusercontent.com/68207888/122847129-37257200-d2d5-11eb-9364-7eac882810ec.png)
![bird](https://user-images.githubusercontent.com/68207888/122847131-37257200-d2d5-11eb-85f0-664e97bb9606.png)
![bookofdeath](https://user-images.githubusercontent.com/68207888/122847132-37be0880-d2d5-11eb-9297-fa9c7e1bb72f.png)
![bookoffrost](https://user-images.githubusercontent.com/68207888/122847133-37be0880-d2d5-11eb-85cb-876fcde08f12.png)
![bookoflightning](https://user-images.githubusercontent.com/68207888/122847134-37be0880-d2d5-11eb-8c56-bd2b37407161.png)
![bookofnature](https://user-images.githubusercontent.com/68207888/122847135-37be0880-d2d5-11eb-900d-3a3e9bc5d6c3.png)
![bookofspirits](https://user-images.githubusercontent.com/68207888/122847136-37be0880-d2d5-11eb-9ef1-0220cc462f5e.png)
![brokenheroshield](https://user-images.githubusercontent.com/68207888/122847138-37be0880-d2d5-11eb-9ea7-5b96e1416b07.png)
![bronzecoin](https://user-images.githubusercontent.com/68207888/122847139-38569f00-d2d5-11eb-9a97-8a007fc2f9b0.png)
![bronzekey](https://user-images.githubusercontent.com/68207888/122847142-38569f00-d2d5-11eb-85eb-f5810a05548d.png)
![bullet](https://user-images.githubusercontent.com/68207888/122847143-38569f00-d2d5-11eb-8996-bab1a28f6f63.png)
![candycane](https://user-images.githubusercontent.com/68207888/122847144-38569f00-d2d5-11eb-8efe-77c0c9f8adc0.png)
![cherryBomb](https://user-images.githubusercontent.com/68207888/122847145-38569f00-d2d5-11eb-8dad-39b788fe9b53.png)
![coinring](https://user-images.githubusercontent.com/68207888/122847146-38569f00-d2d5-11eb-91b9-ffaa3ccfc12a.png)
![darksteelarmor](https://user-images.githubusercontent.com/68207888/122847147-38569f00-d2d5-11eb-9424-f066827276a2.png)
![darksteelhat](https://user-images.githubusercontent.com/68207888/122847148-38ef3580-d2d5-11eb-9cce-4469e092613b.png)
![darksteelhelmet](https://user-images.githubusercontent.com/68207888/122847150-38ef3580-d2d5-11eb-9626-57167889adbc.png)
![Uploading darksteelhood.png…]()

**Comment by maitian352** [comment]
![earthbook3](https://user-images.githubusercontent.com/68207888/122847158-3987cc00-d2d5-11eb-9477-e111d90bbbf0.png)
![earthbook4](https://user-images.githubusercontent.com/68207888/122847159-3987cc00-d2d5-11eb-85c6-d07a04611c90.png)
![earthbook5](https://user-images.githubusercontent.com/68207888/122847160-3987cc00-d2d5-11eb-9389-cf87a0ff36f1.png)
![earthbook6](https://user-images.githubusercontent.com/68207888/122847162-3a206280-d2d5-11eb-995a-4fd92ceae4a2.png)
![earthBullet](https://user-images.githubusercontent.com/68207888/122847163-3a206280-d2d5-11eb-9958-09148c376501.png)
![earthTower](https://user-images.githubusercontent.com/68207888/122847164-3a206280-d2d5-11eb-9b84-c6dd982b3446.png)
![ectocannon](https://user-images.githubusercontent.com/68207888/122847165-3a206280-d2d5-11eb-87aa-7652f6f1b4fb.png)
![ectoglove](https://user-images.githubusercontent.com/68207888/122847167-3a206280-d2d5-11eb-8280-90adbb0b673a.png)
![enchantmentbook](https://user-images.githubusercontent.com/68207888/122847168-3ab8f900-d2d5-11eb-9037-86bda8f2bb00.png)
![favicon](https://user-images.githubusercontent.com/68207888/122847169-3ab8f900-d2d5-11eb-9269-67fa00de320f.png)
![firebook1](https://user-images.githubusercontent.com/68207888/122847171-3ab8f900-d2d5-11eb-9f33-6c8503df3209.png)
![firebook2](https://user-images.githubusercontent.com/68207888/122847172-3ab8f900-d2d5-11eb-9dab-86ebba1b63dc.png)
![firebook3](https://user-images.githubusercontent.com/68207888/122847173-3ab8f900-d2d5-11eb-988e-546fe2800ff2.png)
![firebook4](https://user-images.githubusercontent.com/68207888/122847174-3ab8f900-d2d5-11eb-9793-fcc3ab17db16.png)
![firebook5](https://user-images.githubusercontent.com/68207888/122847175-3b518f80-d2d5-11eb-97da-75067f391417.png)
![firebook6](https://user-images.githubusercontent.com/68207888/122847176-3b518f80-d2d5-11eb-9d93-8c28e4148e90.png)
![fireBullet](https://user-images.githubusercontent.com/68207888/122847177-3b518f80-d2d5-11eb-8524-da8606ba3e31.png)

**Comment by definitely-nobody-is-here** [comment]
wat

**Comment by maitian352** [comment]
![candycane](https://user-images.githubusercontent.com/68207888/122847275-64722000-d2d5-11eb-803d-a62fd68ee5b6.png)
![cherryBomb](https://user-images.githubusercontent.com/68207888/122847276-64722000-d2d5-11eb-9d33-1475ce002748.png)
![coinring](https://user-images.githubusercontent.com/68207888/122847277-64722000-d2d5-11eb-86d7-8a087dc311df.png)
![darksteelarmor](https://user-images.githubusercontent.com/68207888/122847278-64722000-d2d5-11eb-9109-728b17792419.png)
![darksteelhat](https://user-images.githubusercontent.com/68207888/122847279-650ab680-d2d5-11eb-9f11-334357034098.png)
![darksteelhelmet](https://user-images.githubusercontent.com/68207888/122847280-650ab680-d2d5-11eb-9ef3-bb72faa2968e.png)
![darksteelhood](https://user-images.githubusercontent.com/68207888/122847281-650ab680-d2d5-11eb-80a9-363d8cb9dfa9.png)
![devcoin](https://user-images.githubusercontent.com/68207888/122847282-650ab680-d2d5-11eb-88fd-9a8a36b184ac.png)
![developerbow](https://user-images.githubusercontent.com/68207888/122847283-650ab680-d2d5-11eb-9860-9d0396db8103.png)
![advanceddarksteelbow](https://user-images.githubusercontent.com/68207888/122847242-61772f80-d2d5-11eb-8216-f4fd4666816f.png)
![advanceddarksteelstaff](https://user-images.githubusercontent.com/68207888/122847244-620fc600-d2d5-11eb-8343-215b3b36d789.png)
![advanceddarksteelsword](https://user-images.githubusercontent.com/68207888/122847245-620fc600-d2d5-11eb-9929-81cca0f73c08.png)
![advancedgoldenbow](https://user-images.githubusercontent.com/68207888/122847246-620fc600-d2d5-11eb-8321-db5f1b6f6b0c.png)
![advancedgoldenstaff](https://user-images.githubusercontent.com/68207888/122847247-620fc600-d2d5-11eb-9bd7-6462d66a8e26.png)
![advancedgoldensword](https://user-images.githubusercontent.com/68207888/122847248-620fc600-d2d5-11eb-92cc-96f98587158e.png)
![advancedrubybow](https://user-images.githubusercontent.com/68207888/122847249-620fc600-d2d5-11eb-9d69-afaa18052d4f.png)
![advancedrubystaff](https://user-images.githubusercontent.com/68207888/122847250-62a85c80-d2d5-11eb-98f4-44b2ccd40ff6.png)
![advancedrubysword](https://user-images.githubusercontent.com/68207888/122847251-62a85c80-d2d5-11eb-8e87-7227a4f602ad.png)
![advancedsteelbow](https://user-images.githubusercontent.com/68207888/122847252-62a85c80-d2d5-11eb-99ab-c890a9fe551a.png)
![advancedsteelstaff](https://user-images.githubusercontent.com/68207888/122847253-62a85c80-d2d5-11eb-85d6-ae1e79f8d9ca.png)
![advancedsteelsword](https://user-images.githubusercontent.com/68207888/122847254-62a85c80-d2d5-11eb-80dc-3080f60ebf12.png)
![advancedwoodenbow](https://user-images.githubusercontent.com/68207888/122847255-62a85c80-d2d5-11eb-92b0-1e4d865d395b.png)
![advancedwoodenstaff](https://user-images.githubusercontent.com/68207888/122847256-6340f300-d2d5-11eb-86d7-26e2021e8687.png)
![advancedwoodensword](https://user-images.githubusercontent.com/68207888/122847257-6340f300-d2d5-11eb-85e5-2a66f93aabbc.png)
![ball](https://user-images.githubusercontent.com/68207888/122847258-6340f300-d2d5-11eb-9250-af2a537d3306.png)
![ballBullet](https://user-images.githubusercontent.com/68207888/122847259-6340f300-d2d5-11eb-8dca-0aabad528295.png)
![bird](https://user-images.githubusercontent.com/68207888/122847260-6340f300-d2d5-11eb-83e2-cc5407c4d455.png)
![bookofdeath](https://user-images.githubusercontent.com/68207888/122847262-6340f300-d2d5-11eb-951e-f5e03d6f7884.png)
![bookoffrost](https://user-images.githubusercontent.com/68207888/122847264-6340f300-d2d5-11eb-8da0-e6f3f9be3c62.png)
![bookoflightning](https://user-images.githubusercontent.com/68207888/122847267-63d98980-d2d5-11eb-965c-dde63e532855.png)
![bookofnature](https://user-images.githubusercontent.com/68207888/122847268-63d98980-d2d5-11eb-8114-75ce0fd67d39.png)
![bookofspirits](https://user-images.githubusercontent.com/68207888/122847269-63d98980-d2d5-11eb-8149-c207e30abca2.png)
![brokenheroshield](https://user-images.githubusercontent.com/68207888/122847270-63d98980-d2d5-11eb-8b97-fca1c120a2ce.png)
![bronzecoin](https://user-images.githubusercontent.com/68207888/122847272-63d98980-d2d5-11eb-99db-eb545a587a7c.png)
![bronzekey](https://user-images.githubusercontent.com/68207888/122847273-64722000-d2d5-11eb-928c-321ceb0cf090.png)
![bullet](https://user-images.githubusercontent.com/68207888/122847274-64722000-d2d5-11eb-9781-466a00731f88.png)
asdf
