### ISSUE TITLE
BUG - The game crashes when I get a jump boost lootbox

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#143]
I got a jump boost lootbox and the game crashed. Not sure if this happens with otehr lootboexs

**Comment by maitian352** [comment]
It happens with all lootboxes

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/122994752-bfa81f00-d376-11eb-9d36-2075cb882677.png)

**Comment by maitian352** [comment]
literally unplayable

**Comment by definitely-nobody-is-here** [comment]
That was fixed 1 update ago
