### ISSUE TITLE
Collisions are funky and you can glitch halfway through blocks.

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#15]

**Comment by definitely-nobody-is-here** [comment]
how?

**Comment by maitian352** [comment]
If you hold [A] and [W] keys at a wall, you are displayed inside the wall sometimes.

**Comment by maitian352** [comment]
Screenshot
![image](https://user-images.githubusercontent.com/68207888/116632284-d311ad80-a924-11eb-9283-cfded01c1c94.png)

**Comment by definitely-nobody-is-here** [comment]
good job leaking an update. It's being worked on.

**Comment by maitian352** [comment]
You can also glitch out of the world in the lobby
![image](https://user-images.githubusercontent.com/68207888/116634839-31418f00-a92b-11eb-981e-afeaa191f341.png)

**Comment by definitely-nobody-is-here** [comment]
yes. I know.

**Comment by definitely-nobody-is-here** [comment]
The collisions ARE being worked on and I am aware that these issues exist.
![image](https://user-images.githubusercontent.com/67865358/116635121-ef651880-a92b-11eb-80f9-cc7efbb4daf7.png)

**Comment by maitian352** [comment]
You can glitch through the floor.
![image](https://user-images.githubusercontent.com/68207888/116766176-205e4f80-a9f7-11eb-99f0-55ba503327e9.png)

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/116766201-44219580-a9f7-11eb-9046-840a55ea74bc.png)

**Comment by definitely-nobody-is-here** [comment]
good job exposing your tabs

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/116766557-19d0d780-a9f9-11eb-970d-ecde63515977.png)

**Comment by definitely-nobody-is-here** [comment]
what happened there?

**Comment by maitian352** [comment]
Screenshot that I fell through the map

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/117307358-80695180-ae4e-11eb-9312-394b39ca483c.png)
Even after some improvements to corner collisions it is still possible to fall out of the world (just much less often) and then there is this.

**Comment by definitely-nobody-is-here** [comment]
Rubber banding is also possible where you would go into the ground one tick and then get correctly placed outside of it. It's kind of ugly.

**Comment by maitian352** [comment]
F

**Comment by maitian352** [comment]
F

**Comment by definitely-nobody-is-here** [comment]
This issue has been fixed.
