### ISSUE TITLE
BUG - map wierd

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [definitely-nobody-is-here/BattleBoxes_Multiplayer#153]
**Describe the bug**
a lot of stuff is not clear don game join.
* map does not reset to lobby
* banners stay
* bullets are not cleared
* wierd

**To Reproduce**
1. thing

**Expected behavior**
should clear

**Screenshots**
![image](https://user-images.githubusercontent.com/67865358/123570340-00000680-d796-11eb-9d12-46293adcc4d6.png)

**Environment**
 - Browser chrome 90
 - Version v1.4.0

**Additional context**
none

**Comment by maitian352** [comment]
still happens, and now i glith out of hte world
