### ISSUE TITLE
BUG - Autorespawn hack

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [definitely-nobody-is-here/BattleBoxes_Multiplayer#154]
**Describe the bug**
if you set a specific variable to true you can respawn yourself and move

**To Reproduce**
1. confidential?

**Expected behavior**
server should check

**Screenshots**
no

**Environment**
 - Browser MeadowGuarder
 - Version v1.4.0

**Additional context**
no

**Comment by maitian352** [comment]
jUsST yOuSE eTt oOnN SeRVser sWIde!1!1
