### ISSUE TITLE
BUG - loading screen weird

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#176]
**Describe the bug**
loadig screen is out of 32 not 16

**To Reproduce**
idk
i had two tabs open
in game
one of them i closed
the otehr one now has 32 loading

**Expected behavior**
16 loading

**Screenshots**
![image](https://user-images.githubusercontent.com/68207888/125207903-47d66180-e25d-11eb-8552-7cdb9adbe854.png)

**Comment by definitely-nobody-is-here** [comment]
what version?

**Comment by maitian352** [comment]
battleboxes.herokuapp.com

**Comment by definitely-nobody-is-here** [comment]
that is outdated
