### ISSUE TITLE
Client receives all actual ids for other players, creating opportunities to impersonate other players

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [definitely-nobody-is-here/BattleBoxes_Multiplayer#18]
it is possible to set your socket id to someone else's and hack them, and then be able to control their player.
The client knows all actual id's for all players

**Comment by maitian352** [comment]
Ooh, good! I have to make a hack for this.

**Comment by definitely-nobody-is-here** [comment]
well, it's already been fixed.
