### ISSUE TITLE
Server TPS runs at about 75% of set TPS.

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [definitely-nobody-is-here/BattleBoxes_Multiplayer#19]
When the server TPS is set to 60, it runs at about 45 TPS. The collisions are not causing the issue, and neither is the player or bullet calculations. It is very likely that the server simply cannot send those packets fast enough because, even on the server-side, it is reporting at around 45 TPS.
![image](https://user-images.githubusercontent.com/67865358/116007604-8c4b4d00-a5de-11eb-9265-1d2c0a55598c.png)

**Comment by maitian352** [comment]
image says 44 tps

**Comment by definitely-nobody-is-here** [comment]
I can't find the problem, it appears that the server is just unable to go that fast.

**Comment by definitely-nobody-is-here** [comment]
A heroku server ran the game at 60 tps, so this is just a performance limit placed by Windows. Can't bypass it.
