### ISSUE TITLE
you have 63% css??????? I only have 7.5%!!!!!!

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#2]
![Screenshot (302)](https://user-images.githubusercontent.com/68207888/93375657-801c3780-f826-11ea-935e-c94cb903b164.png)

**Comment by maitian352** [comment]
that is the amount of javascript I have

**Comment by maitian352** [comment]
but it changed

**Comment by maitian352** [comment]
when i added more code

**Comment by maitian352** [comment]
Changed:
![image](https://user-images.githubusercontent.com/68207888/101910602-2b6e2b80-3b8d-11eb-9762-33ca11889e8e.png)

**Comment by definitely-nobody-is-here** [comment]
well I have not yet finished with the javascrpit

**Comment by maitian352** [comment]
cool

**Comment by definitely-nobody-is-here** [comment]
also most of your code is just arrays
