### ISSUE TITLE
Canvas blurring when zoomed in too far

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [definitely-nobody-is-here/BattleBoxes_Multiplayer#26]
The canvas is blurred even after turning off image alpha.
![image](https://user-images.githubusercontent.com/67865358/116892175-8b797300-abfd-11eb-9254-2df9ac717aa1.png)

**Comment by definitely-nobody-is-here** [comment]
Apparently, turning on pixelation fixes it but it makes the text blurry and it looks bad

**Comment by definitely-nobody-is-here** [comment]
It's a bit better with the DPR and viewport resolution increase.
![image](https://user-images.githubusercontent.com/67865358/120893252-538c9380-c5e0-11eb-8e0b-56b200385524.png)

**Comment by maitian352** [comment]
AAAAAAAAAAAAAAAAAAAAA its so blurry! everything

if you zoom in and zoo mout in a way
