### ISSUE TITLE
BUG - After changing password the server crashes

### ISSUE THREAD

**Issue by The-God-coder** [definitely-nobody-is-here/BattleBoxes_Multiplayer#44]
When You change your password in the settings menu the server crashes right after

1. Login '...'
2. Go to Settings'...'
3. Change your password 
4. and then the server crashes 

**Expected behavior**
What was expected to happen was to return to the login screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/46657605/117975795-0ed14d80-b2fd-11eb-947e-9402a38bd543.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by definitely-nobody-is-here** [comment]
Ok, it appears that there is a typo of sorts somewhere in the overwrite code for the passwords. This issue has been found by the server and the server has stopped automatically.

**Comment by definitely-nobody-is-here** [comment]
This issue will be solved in the following v0.7.0 update.
