### ISSUE TITLE
BUG - blank names in score table when there are less players ingame than there are connected

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [definitely-nobody-is-here/BattleBoxes_Multiplayer#45]
**Describe the bug**
When there are players connected but some are not ingame it causes blank names in the score table. Sometimes you end up with an empty name, other times, two. The scores are correctly displayed but the player names are not.

**To Reproduce**
1. Open multiple tabs
2. Make some join the game, others not
3. Make a kill
4. offset and things

**Expected behavior**
The score table should only contain players that are in game

**Screenshots**
![image](https://user-images.githubusercontent.com/67865358/118405368-a01a2a00-b645-11eb-827c-20c6f2f5dab1.png)

**Environment**
 - Chrome 90
 - v0.4.1 or later

**Additional context**
This issue was originally about server crashes causing it but on further inspection it is actually just an oversight.

**Comment by definitely-nobody-is-here** [comment]
Confirmation: it only happens when the server crashes.

**Comment by maitian352** [comment]
Can you make the client disconnect after the server crashes?

**Comment by definitely-nobody-is-here** [comment]
**ORIGINAL(ish) ISSUE**

**Describe the bug**
When the server stops, and the client tabs are still open, restarting the server will cause an offset in the score table. Sometimes you end up with an empty name, other times, two. The scores are correctly displayed but the player names are not.

**To Reproduce**
Steps to reproduce the behavior:
1. Open multiple tabs all in a game
2. Crash server somehow (deliberate crash by invalid code?)
3. DO NOT CLOSE OR RELOAD TABS
4. restart server
5. restart the game without closing tabs, just reload
6. kill a player

**Expected behavior**
the server should have a clear player list and not some random blank null thing in the player list.

**Screenshots**
![image](https://user-images.githubusercontent.com/67865358/118405368-a01a2a00-b645-11eb-827c-20c6f2f5dab1.png)

**Environment**
 - Chrome 90
 - v0.4.1 or later

**Additional context**
Having tabs open during server restarts always makes problems. (maybe reloading on second connection will fix it?)

**Comment by definitely-nobody-is-here** [comment]
yay fixed
