### ISSUE TITLE
BUG - Stuttering and hitching and eventual game crash

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [definitely-nobody-is-here/BattleBoxes_Multiplayer#46]
**Describe the bug**
After a while, errors start to appear and build up in the console and as that happens the game hitches, the server slows down, and eventually everything hangs and crashes. It starts as buffering on client side for some slower computers, and then the game goes unresponsive. The game actually also crashes when someone wins.

Sometimes there are connection refused errors.

**To Reproduce**
1. Join with multiple players
2. Play normally for a few minutes
3. Check console every minute
4. Game will start hitching (depends on computer)
5. Crash. Server is fine-ish but clients are not.

**Expected behavior**
The game should not stutter this much

**Screenshots**
![image](https://user-images.githubusercontent.com/67865358/118419759-f198d800-b68a-11eb-80ec-85eba68d4fa1.png)
![Screenshot (31151)](https://user-images.githubusercontent.com/67865358/118421819-da101e00-b68f-11eb-855d-85c233543691.png)
![Screenshot (31154)](https://user-images.githubusercontent.com/67865358/118421828-df6d6880-b68f-11eb-9b9d-58117deb0cb1.png)
**Videos**
[Video (hitching happens at about 1:45)](https://youtu.be/YLCuXAEYvog)
[Video 2 ](https://youtu.be/9t5lPo3HZdQ)

**Environment**
 - Browser Chrome 90
 - Version v0.7.0

**Additional context**
MUST FIX QUICKLY,, GAME UNPLAYEABLE

**Comment by maitian352** [comment]
Here is a videio
https://drive.google.com/file/d/1PFKKBmoWjit_sS8hBOuFCYVEJWfi3gt_/view?usp=sharing

**Comment by definitely-nobody-is-here** [comment]
It seems like the BULLET_LIST is not being being cleared, and over time bullets accumulate and end up piling up until the server is updating thousands of bullets per tick. ![image](https://user-images.githubusercontent.com/67865358/118559957-bfdd4b00-b736-11eb-9ffe-0f66eb09a712.png)

**Comment by definitely-nobody-is-here** [comment]
whoops

**Comment by definitely-nobody-is-here** [comment]
Fixed, the problem was that while reformatting code some variables were not changed. Somehow there were no errors.
