### ISSUE TITLE
BUG - You can't see the scoreboard

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#56]
**Describe the bug**
The scoreboard is not visable

**To Reproduce**
Lose a game
Go to the main menu
Rejoin
The scoreboard is now invisible

**Expected behavior**
The scoreboard should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/68207888/120054026-8e4c6580-bffb-11eb-930d-d29de5226050.png)

**Environment**
 - Browser SP
 - Version Sp.SP.sp_2

**Additional context**
NONE

**Comment by definitely-nobody-is-here** [comment]
definitely-nobody-is-here added a commit that referenced this issue N days ago
v1.1.0 - Bot system and smoother game
