### ISSUE TITLE
BUG - Statistics are bugged

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#57]
**Describe the bug**
The statistics show as 0

**To Reproduce**
idk

**Expected behavior**
The statistics should show the correct numbers

**Screenshots**
![image](https://user-images.githubusercontent.com/68207888/120054126-22b6c800-bffc-11eb-8554-e9c922fffa58.png)
![image](https://user-images.githubusercontent.com/68207888/120054129-25192200-bffc-11eb-9862-c5f73c5b71e6.png)

**Environment**
 - Browser [e.g. Chrome 90, Safari, Edge]
 - Version [e.g. v0.4.3]

**Additional context**

**Comment by definitely-nobody-is-here** [comment]
Conclusion: This is only your account. It has been reset and should work now.
