### ISSUE TITLE
the buttons are stacked

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#58]
![image](https://user-images.githubusercontent.com/68207888/120054294-14b57700-bffd-11eb-8fd7-4b7d566077ba.png)

**Comment by definitely-nobody-is-here** [comment]
how you do?
fill uout thing

**Comment by definitely-nobody-is-here** [comment]
definitely-nobody-is-here added a commit that referenced this issue N days ago
v1.1.0 - Bot system and smoother game
