### ISSUE TITLE
This link will end up redirecting the website instead of opening a new tab

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#59]
1. It's frustrating having to reopen the tab or go click back and then open another tab and open the link in that tab or having to control-click the link
2. you literally only need target="_blank" to make it open it in a new tab. It's not hard.

this link
![image](https://user-images.githubusercontent.com/68207888/120054625-06685a80-bfff-11eb-82f0-4d7a2d83e60c.png)

**Comment by definitely-nobody-is-here** [comment]
Wrong repository
go here
https://github.com/definitely-nobody-is-here/BBmulti_Announcements
