### ISSUE TITLE
BUG - Score board borken again

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#71]
![image](https://user-images.githubusercontent.com/68207888/120874248-daefed80-c573-11eb-9bbb-0bc7e7223390.png)

**Comment by definitely-nobody-is-here** [comment]
it looks fine

**Comment by maitian352** [comment]
No, my username has 2 points, but the username is displayed as --

**Comment by definitely-nobody-is-here** [comment]
ah

**Comment by definitely-nobody-is-here** [comment]
there is no way that this can happen.
