### ISSUE TITLE
BUG - lol is floating and hurt

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#84]
![image](https://user-images.githubusercontent.com/68207888/120942885-aefe7480-c6f9-11eb-9cdf-9173b0a3edb4.png)
I think this might be because lol is still on the win screen

**Comment by maitian352** [comment]
Also lol stays in the same part of the screen, by that i mean it doesn't move when the camera moves

**Comment by definitely-nobody-is-here** [comment]
THIS ISSUE NEVER EXISTED IT WAS PATCHED BEFORE UPDATE RELEASED HOW U GET WHAT VERSION IS THIS

**Comment by definitely-nobody-is-here** [comment]
ALSO IT HAS AN ISSUE ALREADY

**Comment by maitian352** [comment]
color
