### ISSUE TITLE
aaaaaaaaaaaa helmp i broke the game

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#87]
![image](https://user-images.githubusercontent.com/68207888/120946023-1243d300-c709-11eb-99d9-c20ad511a778.png)

**Comment by definitely-nobody-is-here** [comment]
lol

**Comment by maitian352** [comment]
HOW DO I FIX THE GAME aaaaaaaAAAAAAA i try type debug() but NO WORK!!!! WOULD NOT BYE AGGAIN!!!! HELMP HDKLFJAS SDLJFLKAFKLDNV7ASJVKD aaaaaaaaaaaaa how i fix
YOU SAY NO FIX
code no work
sadhvlsnaiernfvsaf
