### ISSUE TITLE
u dont have enough issues

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#89]
BRING ISSUeS #1-8 BACK!!!
![Sprites Orange Hat](https://user-images.githubusercontent.com/68207888/121233345-92308100-c860-11eb-81f1-8ff23190e0a8.gif)
![Sprites](https://user-images.githubusercontent.com/68207888/121233348-92308100-c860-11eb-9348-f80148da40bf.gif)

**Comment by maitian352** [comment]
haha old 0.1.1 previews go brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

**Comment by definitely-nobody-is-here** [comment]
how u get those gifs

**Comment by maitian352** [comment]
what do you mean?
 piskel export as gif

**Comment by maitian352** [comment]
PIXEL ART
