### ISSUE TITLE
aaaaaaaaaaaaaaaaaaa update battleboxes.herokuapp.com ALREADY

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/BattleBoxes_Multiplayer#92]
spam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detectionspam-detection

**Comment by definitely-nobody-is-here** [comment]
I ODNt OWN IT

**Comment by maitian352** [comment]
THEN MAKE YOUR OWN HEROKU APP!!!!!!!!!!!!!!!!!!!! 
setInterval(function(){socket.emit('chatInput','GO PLAY MEADOW GUARDER!!! meadowguarder.herokuapp.com' + Math.random());},5000);
